image: golang:1.9
stages:
  - build
  - test

before_script:
  - export CURRENT_BUILD_PATH=$(pwd)
  - go get github.com/tools/godep
  - cd $CURRENT_BUILD_PATH

build-my-project:
  stage: build
  script:
    - godep restore
    - cd
    - godep go build

test-my-project:
  stage: test
  script:
    - godep restore
    - godep go test -v -cover ./...